name: projectzeta
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  mobkit_dashed_border: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2
  faker: ^2.1.0
  build_runner: ^2.4.10
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/svg/