// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/credit_card/credit_card_page.dart' as a2;
import 'app/credit_card/view_all_page.dart' as a3;
import 'app/expense/register/register_page.dart' as a1;
import 'app/home/home_page.dart' as a0;
import 'app/login/login_page.dart' as a5;
import 'app/onboarding/onboarding_page.dart' as a6;
import 'app/splash/splash_page.dart' as a4;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: a0.routeBuilder,
      ),
      RouteEntity(
        key: '/expense/register',
        uri: Uri.parse('/expense/register'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.RegisterPage(),
        ),
      ),
      RouteEntity(
        key: '/credit_card',
        uri: Uri.parse('/credit_card'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a2.CreditCardPage(),
        ),
      ),
      RouteEntity(
        key: '/credit_card/view_all',
        uri: Uri.parse('/credit_card/view_all'),
        routeBuilder: a3.routeBuilder,
      ),
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a4.SplashPage(),
        ),
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a5.LoginPage(),
        ),
      ),
      RouteEntity(
        key: '/onboarding',
        uri: Uri.parse('/onboarding'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a6.OnBoardingPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  expense: (
    path: '/expense',
    register: '/expense/register',
  ),
  creditCard: (
    path: '/credit_card',
    viewAll: '/credit_card/view_all',
  ),
  splash: '/splash',
  login: '/login',
  onboarding: '/onboarding',
);
