// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/credit_card/credit_card_page.dart' as a1;
import 'app/home/home_page.dart' as a0;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a0.HomePage(),
        ),
      ),
      RouteEntity(
        key: '/credit_card',
        uri: Uri.parse('/credit_card'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.CreditCardPage(),
        ),
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  creditCard: '/credit_card',
);
