// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:routefly/routefly.dart';

import 'app/credit_card/credit_card_page.dart' as a1;
import 'app/credit_card/view_all_page.dart' as a2;
import 'app/home/home_page.dart' as a0;

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: a0.routeBuilder,
      ),
      RouteEntity(
        key: '/credit_card',
        uri: Uri.parse('/credit_card'),
        routeBuilder: (ctx, settings) => Routefly.defaultRouteBuilder(
          ctx,
          settings,
          const a1.CreditCardPage(),
        ),
      ),
      RouteEntity(
        key: '/credit_card/view_all',
        uri: Uri.parse('/credit_card/view_all'),
        routeBuilder: a2.routeBuilder,
      ),
    ];

const routePaths = (
  path: '/',
  home: '/home',
  creditCard: (
    path: '/credit_card',
    viewAll: '/credit_card/view_all',
  ),
);
